# This is a basic workflow to help you get started with Actions

name: Notify Teams

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Notify to teams
      run: |
        curl --location --request POST --header 'Content-Type: application/json' --data-raw '{"text":"New PR generated on demo repo"}' ${{ secrets.DEMOHOOK }}
